# application.yml
server:
  port: 8761

eureka:
  client:
    register-with-eureka: false  # Don't register this service with Eureka
    fetch-registry: false        # Don't fetch the registry
  server:
    enable-self-preservation: false  # To prevent Eureka from throwing exceptions during high failure rates
